### ISSUE TITLE
docs request: linking directly to the modules

### ISSUE THREAD

**Issue by aos** [nix-community/srvos#476] opened 2024-08-05 16:19 UTC
Hey y'all - thanks for putting this together. It's been great having a good reference for proper defaults. While I was browsing the docs, I saw that there are references to the code, like so: 

![image](https://github.com/user-attachments/assets/75727568-33e2-48ce-b9e0-b9958ac7f1d4)

Unfortunately, this means that I also need to have a separate tab open to find this particular file and look through it. I see with `mkdocs` you have a variable for the `repo_url`. I attempted to template that in, but it seems like your version of mkdocs doesn't support this feature of Jinja templating, eg. `{{ repo_url }}/blob/main/nixos/hardware/hetzner-cloud/default.nix`. There are plugins for this ([like this one](https://github.com/rosscdh/mkdocs-markdownextradata-plugin)), but I don't know your appetite for going that far. :-)

What are your thoughts on just adding hardcoded links directly to modules in the Github repo? So the above: `nixosModules.hardware-hetzner-cloud` becomes: [`nixosModules.hardware-hetzner-cloud`](https://github.com/nix-community/srvos/blob/main/nixos/hardware/hetzner-cloud/default.nix)? I'm happy to put together a PR for it if so.

**Comment by zimbatm** [comment] 2024-08-05 19:28
Hey aos, thanks for caring about the details, this is going to make future users experience much nicer.

I'm up for enabling the plugin. We actually have it already in the environment, it just wasn't added to the mkdocs plugin list (see numtide/mkdocs-numtide). You could enable it upstream or here.

**Comment by aos** [comment] 2024-08-06 01:44
Hi @zimbatm - looks like you did the hard work already. Thanks :-) I went ahead and sent the change upstream: https://github.com/numtide/mkdocs-numtide/pull/5

Once that's merged in, I can make a PR here to pull in the new input hash and make the change here

**Comment by zowoq** [comment] 2024-08-06 01:59
> I can make a PR here to pull in the new input hash and make the change here.

The docs also seem to be broken in yesterdays flake update by other changes from mkdocs-numtide: https://github.com/nix-community/srvos/pull/475.

**Comment by zimbatm** [comment] 2024-08-06 14:33
thanks @aos, merged!

@zowoq the issue is unrelated, it's because the new plugin is only available in nixos-unstable, but srvos.dev is using nixos-24.05: https://github.com/nix-community/srvos/blob/46a59095dc9228a945bf1ee8160b397eb502ad6c/dev/private/flake.nix#L4C10-L4C15

**Closed** 2024-08-07 15:36 UTC
